In [2]:
import pandas as pd

In [3]:
!pip install faker

Collecting faker
  Downloading Faker-24.11.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.9 MB/s eta 0:00:00[31m3.8 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.4 in /home/hugob/Documentos/HerramientasIA/entorno1/lib/python3.10/site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/hugob/Documentos/HerramientasIA/entorno1/lib/python3.10/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-24.11.0

In [5]:
from faker import Faker
fake = Faker()

In [ ]:
diccionario = {'nombre':fake,name()}

In [6]:
lista = []

In [9]:
for x in range(0,51):
    lista.append({'nombre': fake.name()})

In [10]:
lista

[{'nombre': 'Ryan Johnson'},
 {'nombre': 'Jaime Hubbard'},
 {'nombre': 'Robert Powell PhD'},
 {'nombre': 'Deborah Castaneda'},
 {'nombre': 'Kristy Gonzalez'},
 {'nombre': 'Angela Evans'},
 {'nombre': 'Sheryl Bradley'},
 {'nombre': 'Bianca Cummings'},
 {'nombre': 'Sandra Thompson'},
 {'nombre': 'Marie Callahan'},
 {'nombre': 'Ashley Alvarez'},
 {'nombre': 'Kevin Davis'},
 {'nombre': 'Victoria Baker'},
 {'nombre': 'Terri Cabrera'},
 {'nombre': 'Amanda Hernandez'},
 {'nombre': 'William Sanchez'},
 {'nombre': 'Cynthia Brown'},
 {'nombre': 'Colleen Clark'},
 {'nombre': 'Ashley Murray'},
 {'nombre': 'Lauren Shaffer'},
 {'nombre': 'Michael Rogers'},
 {'nombre': 'Carol Rivera'},
 {'nombre': 'Matthew Wilson MD'},
 {'nombre': 'John Ashley'},
 {'nombre': 'Victoria Johnson'},
 {'nombre': 'Mary Zavala'},
 {'nombre': 'Matthew Dougherty'},
 {'nombre': 'Michael Hayes'},
 {'nombre': 'Alison Diaz DDS'},
 {'nombre': 'John Brown'},
 {'nombre': 'Holly Harmon'},
 {'nombre': 'Allison Compton'},
 {'nombre': 'Diana Benjamin'},
 {'nombre': 'Danielle Newman'},
 {'nombre': 'Melissa Pacheco'},
 {'nombre': 'Susan Daniel'},
 {'nombre': 'Christine Elliott'},
 {'nombre': 'Brenda Huffman'},
 {'nombre': 'Anthony Jones'},
 {'nombre': 'April Cabrera'},
 {'nombre': 'Lindsey Anderson'},
 {'nombre': 'Tracey Wood'},
 {'nombre': 'Michael Robbins'},
 {'nombre': 'Mary Mitchell'},
 {'nombre': 'Peter Campbell'},
 {'nombre': 'John Hammond'},
 {'nombre': 'Daniel Beck'},
 {'nombre': 'Shannon Richards'},
 {'nombre': 'Kaitlyn White'},
 {'nombre': 'Donna Lucas'},
 {'nombre': 'James Taylor'},
 {'nombre': 'Amy Wiggins'},
 {'nombre': 'Benjamin Hart'},
 {'nombre': 'Cristina Francis'},
 {'nombre': 'Jacob Lozano'},
 {'nombre': 'Michael House'},
 {'nombre': 'Miss Susan Nolan'}]

In [12]:
data = pd.DataFrame(lista)

In [13]:
data

               nombre
0        Ryan Johnson
1       Jaime Hubbard
2   Robert Powell PhD
3   Deborah Castaneda
4     Kristy Gonzalez
5        Angela Evans
6      Sheryl Bradley
7     Bianca Cummings
8     Sandra Thompson
9      Marie Callahan
10     Ashley Alvarez
11        Kevin Davis
12     Victoria Baker
13      Terri Cabrera
14   Amanda Hernandez
15    William Sanchez
16      Cynthia Brown
17      Colleen Clark
18      Ashley Murray
19     Lauren Shaffer
20     Michael Rogers
21       Carol Rivera
22  Matthew Wilson MD
23        John Ashley
24   Victoria Johnson
25        Mary Zavala
26  Matthew Dougherty
27      Michael Hayes
28    Alison Diaz DDS
29         John Brown
30       Holly Harmon
31    Allison Compton
32     Diana Benjamin
33    Danielle Newman
34    Melissa Pacheco
35       Susan Daniel
36  Christine Elliott
37     Brenda Huffman
38      Anthony Jones
39      April Cabrera
40   Lindsey Anderson
41        Tracey Wood
42    Michael Robbins
43      Mary Mitchell
44     Peter Campbell
45       John Hammond
46        Daniel Beck
47   Shannon Richards
48      Kaitlyn White
49        Donna Lucas
50       James Taylor
51        Amy Wiggins
52      Benjamin Hart
53   Cristina Francis
54       Jacob Lozano
55      Michael House
56   Miss Susan Nolan

In [14]:
data.to_csv("misdata.csv", index=False)